# Generated by Django 5.2.6 on 2025-10-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars10', '0002_booking_menuitem_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='persons',
            new_name='num_persons',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
