# Generated by Django 5.2.6 on 2025-10-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars10', '0004_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
